config/routes.rb
Rails.application.routes.draw do

  # TODO: routing-filter gem does not currently support Rails 5.1
  # filter :locale, exclude: %r{\A/auth/auth0/callback|/auth/failure}

  match '/auth/set-state', via: :post, to: 'auth0#set_state'
  match '/auth/auth0/callback', via: :get, to: 'auth0#callback'
  match '/auth/failure', via: :get, to: 'auth0#failure'
  match '/user/profile', via: :get, to: 'user_profile#edit'
  match '/user/profile', via: %i[patch post], to: 'user_profile#update'
  match '/login', via: :get, to: 'auth0#login', as: :login
  match '/logout', via: :delete, to: 'auth0#logout', as: :logout

  match '/dashboard', via: :get, to: 'dashboard#index', as: :dashboard
  match '/super-admin', via: :get, to: 'dashboard#super_admin', as: :super_admin

  resources :accounts

  root 'public_pages#home'
end

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%# The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags %>

  <title><%= content_for(:page_title) || "#{t 'application_name'} - #{ t 'company_name'}" %></title>

  <%# http://realfavicongenerator.net/ -%>
  <%= favicon_link_tag('favicons/favicon.ico') if File.exists?(Rails.root.join('app', 'assets', 'images', 'favicons', 'favicon.ico')) %>
  <% %w{32 16}.each do |size| -%>
      <%= favicon_link_tag("favicons/favicon-#{size}x#{size}.png", type: 'image/png', sizes: "#{size}x#{size}") if File.exists?(Rails.root.join('app', 'assets', 'images', 'favicons', "favicon-#{size}x#{size}.png")) %>
  <% end -%>
  <%= favicon_link_tag('favicons/apple-touch-icon.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '180x180') if File.exists?(Rails.root.join('app', 'assets', 'images', 'favicons', 'apple-touch-icon.png')) %>
  <link rel="mask-icon" href='/assets/favicons/safari-pinned-tab.svg' color='#DE0831'>
  <%= favicon_link_tag('/assets/favicons/safari-pinned-tab.svg', rel: 'mask-icon', type: 'image/svg', color: '#DE0831') %>
  <meta name="theme-color" content="#ffffff">

  <%= csrf_meta_tags %>
  <%= state_meta_tag %> <%# Cross site scripting meta tag for Auth0 Lock widget. %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= include_gon(watch: false) if defined? Gon %>
  <%= yield :javascript -%>
</head>

<body class="app">
<div id="application-background"></div>
<header>
  <section class="header">
    <%= link_to fa_bars, 'javascript:;', class: 'app-aside-trigger' %>
    <h1><%= link_to t('application_name'), dashboard_path %></h1>
    <div class="user-toolbar">
      <% content_for :current_user_anchor do -%>
          <div class="text">
            <%= fa_arrow_down classes: 'down' %>
            <%= tag.span current_user.name, class: 'name' %>
          </div>
          <%= tag.span fa_user_circle_o(classes: 'profile-picture'), class: 'profile-picture' %>
      <% end -%>
      <%= content_tag :a, content_for(:current_user_anchor), data: {'jq-dropdown': '#jq-user-profile-dropdown'} %>

      <% content_for :jq_dropdown do # Render at bottom of body. -%>
          <div id="jq-user-profile-dropdown" class="jq-dropdown jq-dropdown-tip jq-dropdown-anchor-right">
            <ul class="jq-dropdown-menu">
              <li><%= link_to "#{fa_pencil(classes: 'fa-fw')} My Profile".html_safe, user_profile_path %></li>
              <% account_id = current_user.app_metadata.fetch('account_ids', []).first -%>
              <% if account_id && policy(Account.new(id: account_id)).edit? -%>
                  <li><%= link_to "#{fa_sliders(classes: 'fa-fw')} Account Settings".html_safe, edit_account_path(account_id) %></li>
              <% end -%>
              <li><%= link_to "#{fa_sign_out(classes: 'fa-fw')} #{t 'logout'}".html_safe, logout_path, method: :delete %></li>
            </ul>
          </div>
      <% end -%>
    </div>
  </section>

  <div id="flash" data-timeout="5000" data-fadeout="1500">
    <% flash.each do |type, message| %>
        <%= content_tag :p, class: "#{type} message" do
          concat link_to '<i class="fa fa-times-circle" aria-hidden="true"></i>'.html_safe, 'javascript:;', class: 'close'
          concat message
        end
        %>
    <% end %>
  </div>
</header>

<aside class="app-nav">
  <div class="logo">
    <%= inline_svg('company-logo.svg', title: 'Home', nocomment: true, class: 'company-logo') %>
  </div>
  <ul>
    <li>
      <% link = "#{fa_tachometer(classes: 'fa-fw fa-2x')} #{content_tag :span, t('app_layout.aside_nav.dashboard'), class: 'label'}".html_safe %>
      <%= link_to(link, dashboard_path, class: 'active') %>
    </li>
    <li>
      <% link = "#{fa_graduation_cap(classes: 'fa-fw fa-2x')} #{content_tag :span, t('app_layout.aside_nav.content'), class: 'label'}".html_safe %>
      <%= link_to(link, 'javascript:;', class: '') %>
    </li>
    <li>
      <% link = "#{fa_key(classes: 'fa-fw fa-2x')} #{content_tag :span, t('app_layout.aside_nav.restricted'), class: 'label'}".html_safe %>
      <%= link_to(link, 'javascript:;', class: '') %>
    </li>
    <% if policy(:dashboard).super_admin? -%>
      <li>
        <% link = "#{fa_user_secret(classes: 'fa-fw fa-2x')} #{content_tag :span, t('app_layout.aside_nav.super_admin'), class: 'label'}".html_safe %>
        <%= link_to(link, super_admin_path, class: '') %>
      </li>
    <% end -%>
  </ul>
</aside>

<% controller_classes = [] -%>
<div id="<%= controller_name.gsub('_', '-') %>" class="<%= controller_classes.join(' ') %>">
  <div id="<%= action_name.gsub('_', '-') %>" class="app-action">
    <%= yield %>
  </div>
</div>

<%# Content for jQuery drop-downs, which must be just before the closing body tag. %>
<%= content_for :jq_dropdown %>
</body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%# The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -%>

  <title>Rails Auth0</title>

  <%# http://realfavicongenerator.net/ -%>
  <%= favicon_link_tag('favicons/favicon.ico') if File.exists?(Rails.root.join('app', 'assets', 'images', 'favicons', 'favicon.ico')) %>
  <% %w{32 16}.each do |size| -%>
      <%= favicon_link_tag("favicons/favicon-#{size}x#{size}.png", type: 'image/png', sizes: "#{size}x#{size}") if File.exists?(Rails.root.join('app', 'assets', 'images', 'favicons', "favicon-#{size}x#{size}.png")) %>
  <% end -%>
  <%= favicon_link_tag('favicons/apple-touch-icon.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '180x180') if File.exists?(Rails.root.join('app', 'assets', 'images', 'favicons', 'apple-touch-icon.png')) %>
  <link rel="mask-icon" href='/assets/favicons/safari-pinned-tab.svg' color='#DE0831'>
  <%= favicon_link_tag('/assets/favicons/safari-pinned-tab.svg', rel: 'mask-icon', type: 'image/svg', color: '#DE0831') %>
  <meta name="theme-color" content="#ffffff">

  <%= csrf_meta_tags %>
  <%= state_meta_tag %> <%# Cross site scripting meta tag for Auth0 Lock widget. %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= include_gon(watch: false) if defined? Gon %>
  <%= yield :javascript %>
</head>

<body class="public">
<div id="application-background"></div>

<header>
  <header>
    <div id="flash" data-timeout="5000" data-fadeout="1500">
      <% flash.each do |type, message| %>
          <%= content_tag :p, class: "#{type} message" do
            concat link_to '<i class="fa fa-times-circle" aria-hidden="true"></i>'.html_safe, 'javascript:;', class: 'close'
            concat message
          end
          %>
      <% end %>
    </div>

    <div class="auth">
      <% unless user_signed_in? -%>
          <script>
              <%# Customization options:  https://github.com/auth0/lock -%>
              var auth0LockOptions = {
                  auth: {
                      redirectUrl: '<%= Rails.application.secrets.auth0_callback_url %>',
                      params: {
                          scope: 'openid email picture user_metadata app_metadata offline_access',
                          state: $('meta[name="state"]').attr('content')
                      }
                  },
                  languageDictionary: {
                      title: 'Rails App'
                  },
                  rememberLastLogin: true,
                  theme: {
                      logo: '/login-logo.svg',
                      primaryColor: '#DE0831'
                  },
                  allowLogin: true,
                  allowSignUp: false
              };
              var auth0Lock = new Auth0Lock('<%= Rails.application.secrets.auth0_client_id %>', '<%= Rails.application.secrets.auth0_domain %>', auth0LockOptions);

              function signin() {
                  auth0Lock.show();
              }
          </script>
          <!--a class="" onclick="signin()">Login</a-->
      <% end -%>
    </div>
  </header>
</header>
<% controller_classes = [] -%>
<div id="<%= controller_name.gsub('_', '-') %>" class="<%= controller_classes.join(' ') %>">
  <div id="<%= action_name.gsub('_', '-') %>">
    <%= yield %>
  </div>
</div>
</body>
</html>