config/routes.rb
Rails.application.routes.draw do

  # TODO: routing-filter gem does not currently support Rails 5.1
  # filter :locale, exclude: %r{\A/auth/auth0/callback|/auth/failure}

  match '/auth/set-state', via: :post, to: 'auth0#set_state'
  match '/auth/auth0/callback', via: :get, to: 'auth0#callback'
  match '/auth/failure', via: :get, to: 'auth0#failure'
  match '/user/profile', via: :get, to: 'user_profile#edit'
  match '/user/profile', via: %i[patch post], to: 'user_profile#update'
  match '/login', via: :get, to: 'auth0#login', as: :login
  match '/logout', via: :delete, to: 'auth0#logout', as: :logout

  match '/dashboard', via: :get, to: 'dashboard#index', as: :dashboard
  match '/super-admin', via: :get, to: 'dashboard#super_admin', as: :super_admin

  resources :accounts

  root 'public_pages#home'
end

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/account.rb
# Account model.
#
class Account < ApplicationRecord
  store_accessor :settings, :theme

  validates :name, presence: true, uniqueness: true

  def name=(name)
    name = sanitize(name).squish
    name = nil if name.blank?
    self[:name] = name
  end
end

app/controllers/accounts_controller.rb
# Accounts controller
#
class AccountsController < ApplicationController
  include Secured

  before_action :set_account, only: %i[show edit update destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :account_not_found

  def index
    authorize Account
    @accounts = policy_scope(Account)
  end

  def new
    authorize Account
    @account = Account.new
  end

  def show
    authorize @account
  end

  def edit
    authorize @account if @account
  end

  def update
    authorize @account
    respond_to do |format|
      if @account.update(permitted_attributes(@account))
        format.html { redirect_to @account, notice: 'Account updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  #---------------------------------------------------------------------------
  private

  def set_account
    @account = Account.where(id: params[:id]).first
    raise ActiveRecord::RecordNotFound, 'Account not found' unless @account
  end

  def account_not_found
    redirect_to dashboard_path, alert: 'Account not found'
  end
end

app/views/accounts/_form.html.erb
<%= form_with model: @account, html: { class: 'simple-form' } do |form| %>
    <%= form.label :name %>
    <%= form.text_field :name, placeholder: 'Account name', id: :account_name %>
    <br>
    <%= form.submit %>
<% end -%>

<p>
  <%= link_to "#{fa_arrow_left}&nbsp; Back".html_safe, policy(Account).index? ? accounts_path : dashboard_path %>
</p>

app/views/accounts/edit.html.erb
<%= tag.h1 'Edit account' %>

<%= render partial: 'form' %>

app/views/accounts/index.html.erb
<%= tag.h1 'Accounts' %>

<ul>
  <% @accounts.each do |account| %>
    <%= tag.li do %>
      <% concat link_to account.name, edit_account_path(account) %>
      <% end -%>
  <% end -%>
</ul>

app/views/accounts/new.html.erb
<%= tag.h1 'New account' %>

<%= render partial: 'form' %>

app/views/accounts/show.html.erb
<%= tag.h1 'Edit account' %>

<%= render partial: 'form' %>